### ISSUE TITLE
Job Descriptions should be able to specify their adaptor

### ISSUE THREAD

**Issue by stuartc** [OpenFn/core#18]
- [x] add a column to JobDescriptions for destination adaptor
- [ ] allow Submission Processor to get language pack name from Job
- [x] add dropdown to Job with list of adaptors  
      *for now is only salesforce*

**Comment by taylordowns2000** [comment]
@stuartc , isn't this implicitly handled by the `credential` and the `trigger_id`?

Could the credential be used for fixing the destination adaptor and the trigger_id be used to fix the source adaptor, if there is one?
