### ISSUE TITLE
Rename Submissions created_at column to inserted_at

### ISSUE THREAD

**Issue by stuartc** [OpenFn/core#19]

**Comment by taylordowns2000** [comment]
@stuartc , can i grab this?

**Comment by taylordowns2000** [comment]
Done. Note that you can't add timestamps to postgres unless you're using "create table", so I've added the `inserted_at` and `updated_at` fields manually. In the model, I've added `timestamps` and they populate correctly. See submission #4 below and compare to correctly timestamped `receipts`.
![image](https://cloud.githubusercontent.com/assets/8732845/11741946/317023f8-9fca-11e5-85f3-66dd8e47e86e.png)
