### ISSUE TITLE
Scope UI pages by User

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/core#27]
This is obviously the big step needed before any clients can login.

- [x] `/submissions` API
- [x] `/job_descriptions` API
- [x] `/receipts` API
- [x] `/credentials` API

**Comment by stuartc** [comment]
@taylordowns2000 The changes are pretty straight forward, I've scoped all the index pages by the current user. Also guardian will now return a 401 if you're not logged in.

It's not perfect, but will help in the short term.

**Comment by taylordowns2000** [comment]
@stuartc , this is perfect. i just added receipt filters as well. your pattern was pretty easy to follow! thanks dude!
