### ISSUE TITLE
Build auto-process feature

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/core#33]

**Comment by stuartc** [comment]
- Added autoprocess boolean column to job_descriptions.
  Which is off by default.
- UI not in place yet, so this needs to enabled in the DB until then.
- Inbox posting is now async, meaning the providing system gets an immediate 202
  as long as the inbox exists.

**Comment by taylordowns2000** [comment]
This is great @stuartc . Should we give a 200 once a receipt is inserted? (That's the end of the line as far as the providing system is concerned, and if it succeeds they want to know.) I remember we had issues with CommCare backing off data forwarding because they didn't receive 200s.
