### ISSUE TITLE
Fix inbox controller test and dispatcher test

### ISSUE THREAD

**Issue by taylordowns2000** [OpenFn/core#40]
- [x] inbox_controller_test
- [x] dispatcher_test

**Comment by taylordowns2000** [comment]
Thank you, @stuartc !

**Comment by stuartc** [comment]
@taylordowns2000 was a pain in the ass, but revealed two important points:

- We weren't installing nodejs (or the required node modules) on Travis.
- There was an assumption that `fn-lang` would be available in the `PATH`
  however I have been working with a custom PATH on my machine.
  so CI was revealing that.

However I'm not going to try diagnose why Heroku worked, perhaps they are progressive and have the `./node_modules/.bin` in the `PATH`.
